import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'
import { use } from 'react'
import Link from 'next/link'
import AutocompleteSearch from './components/AutoCompleteSearch'
import CityList from './components/CityList'

const sora = Sora({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
async function getCityList() {
  const res = await fetch(
    'https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/geonames-all-cities-with-a-population-1000/records?limit=20',
    {
      cache: 'force-cache',
    }
  )
  return await res.json()
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={sora.className + ' p-6 rain'}>
        {/* <div className="absolute bottom-[50%] z-[3] right-[30%] bg-[var(--primary)] h-[20vh] w-[20vw] rounded-[50%]"></div> */}
        <div className="absolute top-[50px] z-[3] left-[30%] bg-blue-500 h-[60vh] w-[30vw] rounded-[50%]"></div>
        <div className="absolute top-[50px] z-[3] left-[10%] bg-sky-500 h-[30vh] w-[30vw] rounded-[50%]"></div>
        <div className="absolute top-[50%] z-[3] left-[10%] bg-blue-900 h-[20vh] w-[30vw] rounded-[50%]"></div>
        <div className="absolute bottom-[100px] z-[3] left-[50%] bg-sky-500 h-[20vh] w-[30vw] rounded-[50%]"></div>
        <div className="grid gap-4 grid-cols-1 lg:grid-cols-[1fr_270px] xl:grid-cols-[1fr_400px] min-h-[500px] bg-white/10 rounded-3xl relative z-[5] backdrop-blur-[200px]">
          {children}
          <div>
            <CityList />
          </div>
        </div>
      </body>
    </html>
  )
}
